---

#    ansible-playbook ad-hoc-alb/uninstall/uninstall-alb-purge.yml -i example.com,example.org

- name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml"
  hosts: all
  gather_facts: no

  vars:
  
    alb_paths_real:
      - /opt/alb/ # This folder contain symlinks to most of other folder next on this list
      - /var/app/
      - /var/alb/
      - /etc/resty-auto-ssl/letsencrypt/
      - /var/log/sysapp/
      - /var/log/app/
      - /etc/haproxy/
      - /var/sysapp/
      - /usr/local/openresty/nginx/
      - /var/log/alb/

  vars_prompt:
    - name: agree
      prompt: "DID YOU REALLY WANT APPLY uninstall-alb-purge.yml: TO {{ ansible_play_hosts }}? (yes/no)"
      private: no

    - name: backup
      prompt: "Can I make a backup of configurations and logs at /var/backups/alb-DATETIME.tar.gz? (yes/no)"
      default: yes
      private: no

  pre_tasks:
    - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | agree?"
      fail:
        msg: "User did not explicitly agree, aborting"
      when: "agree != 'yes' and agree != 'y'"

  tasks:
    - set_fact:
        backup_datetime: "{{ ansible_date_time.iso8601_micro }}"
    - set_fact:
        backup_destiny_mainfolder: "/var/backups/alb-root-{{ backup_datetime }}.tar.xz"
        backup_destiny_realfolders: "/var/backups/alb-real-{{ backup_datetime }}.tar.xz"

    - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | xz format require destiny already exist {{ backup_destiny_realfolders }}"
      file:
        path: "{{ backup_destiny_realfolders }}"
        state: touch
      when:
        - "backup|bool"

    - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | create backup at {{ backup_destiny_realfolders }}"
      archive:
        path: "{{ alb_paths_real }}"
        dest: "{{ backup_destiny_realfolders }}"
        format: xz
      register: backup_task_real
      when:
        - "backup|bool"

    - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | How to list the concents of the backup file:"
      debug:
        msg: "tar -Jtvf {{ backup_destiny_realfolders }}"
      when:
        - "backup|bool"

    # - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | backup_task info"
    #   debug:
    #     msg: "{{ backup_task_real }}"
    #   when:
    #     - "backup|bool"

    # - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | create backup at {{ backup_destiny_mainfolder }}"
    #   archive:
    #     path: /opt/alb
    #     dest: "{{ backup_destiny_mainfolder }}"
    #     format: xz
    #   register: backup_task_main
    #   when:
    #     - "backup|bool"

    # - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | How to list the concents of the backup file:"
    #   debug:
    #     msg: "tar -Jtvf {{ backup_task_main }}"
    #   when:
    #     - "backup|bool"

    # - name: "ad-hoc-alb | uninstall | uninstall-alb-purge.yml | backup_task info"
    #   debug:
    #     msg: "{{ backup_task_main }}"
    #   when:
    #     - "backup|bool"

