---

#    ansible-playbook ad-hoc-alb/uninstall-alb-purge.yml -i example.com,example.org

- name: "We EXPLICITLY include the script of backup-alb-full.yml, so the user should really opt out for backup before total purge"
  import_playbook: backup-alb-full.yml

- name: "ad-hoc-alb | uninstall-alb-purge.yml (THIS WILL PURGE OPENRESTY, HAPROXY COMMON PATHS USED BY AP-ALB, but will ignore UFW, Consul, Redis, ...)"
  hosts: all
  gather_facts: no

  vars:

    alb_paths_real:
      - /opt/alb/ # This folder contain symlinks to most of other folder next on this list
      - /var/app/
      - /var/alb/
      - /etc/resty-auto-ssl/letsencrypt/
      - /var/log/sysapp/
      - /var/log/app/
      - /etc/haproxy/
      - /var/sysapp/
      - /usr/local/openresty/nginx/
      - /var/log/alb/

    # These files maybe will not exist on every installation
    alb_paths_spefialfiles:
      - /etc/ansible/facts.d/alb_apps.fact
      - /etc/ansible/facts.d/alb_common.fact
      - /etc/ansible/facts.d/alb_haproxy.fact
      - /etc/ansible/facts.d/alb_lastrun.fact
      - /etc/ansible/facts.d/alb_openresty.fact
      - /etc/ansible/facts.d/alb_sysapps.fact
      - /etc/ansible/facts.d/alb_ufw.fact
      - /etc/logrotate.d/alb_apps
      - /etc/logrotate.d/alb_sysapps
      - /etc/logrotate.d/alb

  vars_prompt:
    - name: agree
      prompt: "DID YOU REALLY WANT APPLY uninstall-alb-purge.yml: TO {{ ansible_play_hosts }}? (yes/no)"
      private: no

  pre_tasks:
    - name: "ad-hoc-alb | uninstall-alb-purge.yml | agree?"
      fail:
        msg: "User did not explicitly agree, aborting"
      when: "agree != 'yes' and agree != 'y'"

  tasks:

    - name: "ad-hoc-alb | uninstall-alb-purge.yml | openresty"
      apt:
        name: openresty
        state: absent
        purge: yes

    - name: "ad-hoc-alb | uninstall-alb-purge.yml | haproxy"
      apt:
        name: haproxy
        state: absent
        purge: yes

    - name: "ad-hoc-alb | uninstall-alb-purge.yml | delete directories {{ alb_paths_real }}"
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ alb_paths_real }}"

    - name: "ad-hoc-alb | uninstall-alb-purge.yml | delete special files {{ alb_paths_spefialfiles }}"
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ alb_paths_spefialfiles }}"

