---

# TODO: update this example to add more features created after the v0.4+ (fititnt, 2019-11-07 19:00)

- name: "ap-application-load-balancer playbook example (complex)"
  hosts: my_complex_hosts
  remote_user: root
  vars:
    alb_name: "MyALBName/2.0"
    alb_forcedebug: yes

    alb_haproxy_stats_enabled: yes

    alb_acme_rule_whitelist:
       - "example.net"
       - "www.example.com"
       - "*.example.org"
    # /var/alb/domains_blacklist.txt
    alb_acme_rule_blacklist:
       - "let-ssl-expire.example.net"
       - "dont-ask-letsencrypt.example.com"

    ## Uncomment next line if you are debugging Let's encrypt (and do not want hit limits on Production)
    # alb_acme_url: "https://acme-staging-v02.api.letsencrypt.org/directory"

    # Apps
    alb_apps:

      - app_uid: "static-home-page"
        app_domain: "www.example.org"
        app_root: "/var/www/html"
        app_forcehttps: no
        app_alb_strategy: "files-local"

      - app_uid: "minio"
        app_domain: "minio.example.org"
        app_alb_strategy: "proxy"
        app_forcehttps: yes
        app_alb_proxy: ":::9091"

  roles:
    - { role: ap-application-load-balancer }