---

- name: "ap-application-load-balancer example: 1 node fileserver"
  hosts: mnemosine
  remote_user: root
  vars:
    alb_apps:

      - app_uid: "static-home-page"
        app_domain: "www.example.org"
        app_root: "/var/www/html"
        app_forcehttps: no
        app_alb_strategy: "files-local"

      - app_uid: "minio"
        app_domain: "minio.example.org"
        app_alb_strategy: "proxy"
        app_forcehttps: yes
        app_alb_proxy: ":::9091"

  roles:
    - { role: ap-application-load-balancer }