---

- name: "ap-application-load-balancer playbook example (complex)"
  hosts: mnemosine
  remote_user: root
  vars:
    alb_name: "MyALBName/2.0"
    alb_forcedebug: yes

    ## Uncomment next line if you are debugging Let's encrypt (and do not want hit limits on Production)
    # alb_letsencrypt_acmeurl_custom: "https://acme-staging-v02.api.letsencrypt.org/directory"

    # Apps
    alb_apps:

      - app_uid: "static-home-page"
        app_domain: "www.example.org"
        app_root: "/var/www/html"
        app_forcehttps: no
        app_alb_strategy: "files-local"

      - app_uid: "minio"
        app_domain: "minio.example.org"
        app_alb_strategy: "proxy"
        app_forcehttps: yes
        app_alb_proxy: ":::9091"

  roles:
    - { role: ap-application-load-balancer }