---
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  # global:
  #   - ROLE_NAME: my_role_name
  matrix:
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: centos:7

install:
  - pip install testinfra molecule docker

# before_script:
#   - cd ../
#   - mv ap-application-load-balancer fititnt.ap-application-load-balancer
#   - cd fititnt.ap-application-load-balancer

script:
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/