---

# FILE:            {{ role_path }}/tasks/alb-final.yml
# LICENSE:         Public Domain
#
# alb-final tasks runs after other softwares are already installed

- name: /etc/ansible/facts.d/alb_apps.fact
  template:
    # src: "{{ role_path }}/templates/openresty/nginx/conf/nginx.conf.j2"
    src: files/alb_apps.fact
    dest: /etc/ansible/facts.d/alb_apps.fact
    mode: '0644'
