---
# FILE:            {{ role_path }}/tasks/alb-final.yml
# LICENSE:         Public Domain
#
# alb-final tasks runs after other softwares are already installed

# Tip: to discover the facts on all hosts, run
#    ansible all -m setup -a "filter=ansible_local" -i hosts

- name: "/etc/ansible/facts.d/alb_lastrun.fact (Only alb_manange_sanitycheck: yes /  alb_manange_sanitycheck: yes will not deploy this fact)"
  template:
    src: files/alb_lastrun.fact
    dest: /etc/ansible/facts.d/alb_lastrun.fact
    mode: 0755
  when: (alb_manange_haproxy is sameas true) or (alb_manange_openresty is sameas true) or (alb_manange_ufw is sameas true) or (alb_manange_common is sameas true) or (alb_manange_devtools is sameas true) or (alb_manange_apps is sameas true) or (alb_manange_logrotate is sameas true) 

# Moved to Apps
#- name: /etc/ansible/facts.d/alb_apps.fact
#  template:
#    src: files/alb_apps.fact
#    dest: /etc/ansible/facts.d/alb_apps.fact
#    mode: 0755
#  when:
#    - alb_manange_apps is sameas true

# Moved to UFW
#- name: /etc/ansible/facts.d/alb_ufw.fact
#  template:
#    src: files/alb_ufw.fact
#    dest: /etc/ansible/facts.d/alb_ufw.fact
#    mode: 0755
#  when:
#    - alb_manange_ufw is sameas true
