---

# FILE:            {{ role_path }}/tasks/default-files.yml
# LICENSE:         Public Domain

#- name: mkdir -p /usr/local/openresty/nginx/conf/sites-available
#  file:
#    path: /usr/local/openresty/nginx/conf/sites-available
#    state: directory
#    mode: '0644'
#    # recurse: yes

#- name: mkdir -p /usr/local/openresty/nginx/conf/sites-enabled
#  file:
#    path: /usr/local/openresty/nginx/conf/sites-enabled
#    state: directory
#    mode: '0644'
    # recurse: yes

#- name: mkdir {{ alb_logs_path }}
#  file:
#    path: "{{ alb_logs_path }}"
#    state: directory
#    mode: '0644'
#    recurse: yes
#  when: alb_logs_method is defined and alb_logs_method == "file"

- name: /usr/local/openresty/nginx/html/index.html
  template:
    src: "{{ role_path }}/templates/openresty/nginx/html/index.html.j2"
    dest: /usr/local/openresty/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/favicon.ico
  template:
    src: "{{ role_path }}/templates/openresty/nginx/html/favicon.ico"
    dest: /usr/local/openresty/nginx/html/favicon.ico
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/robots.txt
  template:
    src: "{{ role_path }}/templates/openresty/nginx/html/robots.txt"
    dest: /usr/local/openresty/nginx/html/robots.txt
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/404.html
  template:
    src: "{{ role_path }}/templates/openresty/nginx/html/404.html.j2"
    dest: /usr/local/openresty/nginx/html/404.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/50x.html
  template:
    src: "{{ role_path }}/templates/openresty/nginx/html/50x.html.j2"
    dest: /usr/local/openresty/nginx/html/50x.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/conf/nginx.conf
  template:
    # src: "{{ role_path }}/templates/openresty/nginx/conf/nginx.conf.j2"
    src: "{{ alb_nginxconf_template }}"
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - reload openresty
