---

# FILE:            {{ role_path }}/tasks/apps.yml
# LICENSE:         Public Domain

## NGinx Server Blocks (e.g. ~Apache Virtual Hosts)
#- name: "NGinx Server Blocks (e.g. ~Apache Virtual Hosts)"
#  template:
#    src: "{{ item.vhost_template|default(alb_apps_serverblock_template) }}"
#    dest: "/usr/local/openresty/nginx/conf/sites-enabled/{{ item.domain }}.conf"
#    owner: root
#    group: "root"
#    mode: 0644
#    backup: yes
#  with_items: "{{ alb_apps }}"
#  notify: reload openresty

- name: "ALB App Rules"
  template:
    # src: "{{ item.vhost_template|default(alb_apps_serverblock_template) }}"
    src: "{{ role_path }}/templates/alb-strategy/{{ item.app_alb_strategy }}.conf.j2"
    dest: "/usr/local/openresty/nginx/conf/sites-enabled/{{ item.app_uid }}.conf"
    owner: root
    group: "root"
    mode: 0644
    backup: yes
  with_items: "{{ alb_apps }}"
  notify: reload openresty