---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

# @see https://docs.ansible.com/ansible/latest/modules/apt_module.html

- name: Instalação de OpenResty, Lua Rest & Lua Resty AutoSSL (faz o HTTPS para os Apps)
  include: openresty-luarocks-lua-resty-auto-ssl-install.yml

- name: Arquivos padrões do OpenResty
  include: default-files.yml

- name: ALB rule for each App
  include: apps.yml
  tags:
  - alb
  - alb-app

- name: HAproxy
  include: haproxy.yml
  tags:
  - alb-haproxy

#- name: Sites HTML estático
#  include: sites-static.yml
#  tags:
#  - serverblocksetup

#- name: Sites HTML estático
#  import_tasks: site-static.yml
#  #loop: "{{ openrestyautossl_sites_static | dict2items }}"
#  tags:
#  - serverblocksetup