---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

- name: alb-vars.yml (temporary file, will be replaced later)
  include: alb-vars.yml
  tags:
  - alb
  - alb-init
  - alb-vars

- name: alb-init.yml
  include: alb-init.yml
  tags:
  - alb
  - alb-init

- name: Instalação de OpenResty, Lua Rest & Lua Resty AutoSSL (faz o HTTPS para os Apps)
  include: openresty-luarocks-lua-resty-auto-ssl-install.yml
  tags:
  - alb
  - alb-openresty

- name: alb-openresty-after.yml
  include: alb-openresty-after.yml
  tags:
  - alb
  - alb-openresty-after

# ansible-playbook -i hosts myplaybook.yml --skip-tags "alb-openresty,alb-app,alb-extra-php"
- name: HAproxy
  include: haproxy.yml
  tags:
  - alb
  - alb-haproxy
  when: alb_forceignore_haproxy is defined and alb_forceignore_haproxy != true

- name: ALB rule for each App
  include: apps.yml
  tags:
  - alb
  - alb-app

- name: logrotate.yml
  include: logrotate.yml
  tags:
  - alb
  - alb-logrotate

- name: alb-final.yml
  include: alb-final.yml
  tags:
  - alb
  - alb-final