---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

- name: alb-init.yml
  include: alb-init.yml
  tags:
  - alb
  - alb-init

- name: Instalação de OpenResty, Lua Rest & Lua Resty AutoSSL (faz o HTTPS para os Apps)
  include: openresty-luarocks-lua-resty-auto-ssl-install.yml
  tags:
  - alb
  - alb-openresty

- name: alb-openresty-after.yml
  include: alb-openresty-after.yml
  tags:
  - alb
  - alb-openresty-after

# ansible-playbook -i hosts myplaybook.yml --skip-tags "alb-openresty,alb-app,alb-extra-php"
- name: HAproxy
  include: haproxy.yml
  tags:
  - alb
  - alb-haproxy
  when: alb_forceignore_haproxy is defined and alb_forceignore_haproxy != true

# TODO: break default-files.yml in multiple files (fititnt, 2019-08-04 01:34 BRT)
#- name: Arquivos padrões do OpenResty
#  include: default-files.yml
#  tags:
#  - alb
#  - alb-openresty

# ansible-playbook -i hosts myplaybook.yml --skip-tags "alb-openresty,alb-app,alb-haproxy"
# ansible-playbook -i hosts eticaai-data-warehouse.yml --skip-tags "alb-openresty,alb-app,alb-haproxy"
# - name: "AP-ALB++: setup local installation of PHP-FPM (Use ppa:ondrej/php)"
#  include: extra-php.yml
#  tags:
#  - alb
#  - alb-extra-php
#  when: alb_forceignore_extra_php is defined and alb_forceignore_extra_php != true
#  # when: alb_extra_php is defined and alb_extra_php.enabled is defined and alb_extra_php.enabled == true

- name: ALB rule for each App
  include: apps.yml
  tags:
  - alb
  - alb-app

#- name: Sites HTML estático
#  include: sites-static.yml
#  tags:
#  - serverblocksetup

#- name: Sites HTML estático
#  import_tasks: site-static.yml
#  #loop: "{{ openrestyautossl_sites_static | dict2items }}"
#  tags:
#  - serverblocksetup

- name: alb-final.yml
  include: alb-final.yml
  tags:
  - alb
  - alb-final