---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

## AP-ALB v0.8.x adaptations to support RHEL/CentOS 8 family and design changes to allow flexibility even for non-tested OSs #34
##   - https://github.com/fititnt/ap-application-load-balancer/issues/34
##   - https://linuxize.com/post/how-to-install-python-on-centos-8/
##   - https://www.linuxschoolonline.com/how-to-use-ansible-even-it-the-target-host-does-not-have-python-installed/
##   - https://medium.com/@somakdas/simple-ansible-paybook-without-python-installed-in-target-machines-1df423004da5
##   - https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/commands/#when-all-else-fails

# About tags https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html

# ansible -m raw -s -a "sudo dnf install python3 -y" aguia-pescadora-delta.etica.ai

# OpenResty https://openresty.org/en/linux-packages.html

- name: "ALB Info"
  debug: 
    msg:
      alb_version: "{{ alb_version }}"
      node:
        os: "{{ ansible_os_family | default('undefined') | lower }}"
        dist: "{{ ansible_distribution | default('undefined') | lower }}"
        dist_major_ver: "{{ ansible_distribution_major_version | default('undefined') | lower }}"
  tags:
    - alb
    - always

## Variable loading based on node Operational System ___________________________
- name: "ALB | OS Family variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_osfamily is defined) | ternary(alb_vars_osfamily,'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/{{ ansible_os_family | default('undefined') | lower }}.yml"
    - "os-family/{{ (ansible_os_family is defined) | ternary('untested','unknown') }}.yml"
  tags:
    - alb
    - always

- name: "ALB | Distribution variables (may override OS Family variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_distribution is defined) | ternary(alb_vars_distribution, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/{{ ansible_distribution | default('undefined') | lower }}.yml"
    - "os-family/distribution/no-os-family-customization.yml"
  tags:
    - alb
    - always

- name: "ALB | Specific version distribution variables (may override OS Family and Distribution variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_distribution_version is defined) | ternary(alb_vars_distribution_version, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/version/{{ ansible_distribution | default('undefined') | lower }}-{{ ansible_distribution_major_version | default('undefined') | lower }}.yml"
    - "os-family/distribution/version/no-distribution-customization.yml"
  tags:
    - alb
    - always

## Run each ALB subcomponent ___________________________________________________

- name: "bootstrap/main.yml"
  include: bootstrap/main.yml
  tags:
    - alb
    - alb-bootstrap
  when:
    - alb_manange_all is sameas true
    - alb_manange_bootstrap is sameas true

- name: "ALB | Abort if running in Unknow state"
  fail:
    msg: "{{ alb_internal_alert_critical_all }}"
  tags:
    - always
  when:
    - alb_internal_alert_critical_all is defined

- name: "ALB: check the version of last run on /etc/ansible/facts.d/alb_lastrun.fact (main)"
  set_fact:
    alb_version_lastrun: "{{ ansible_facts['ansible_local']['alb_lastrun']['alb_version'] }}"
  tags:
    - always
  when:
    - ansible_facts['ansible_local'] is defined and ansible_facts['ansible_local']['alb_lastrun'] is defined and ansible_facts['ansible_local']['alb_lastrun']['alb_version'] is defined
    - alb_version_lastrun|int != -1

- name: "sanitycheck/main.yml"
  include: sanitycheck/main.yml
  tags:
    - alb
    - alb-sanitycheck
  when:
    - alb_manange_all is sameas true
    - alb_manange_sanitycheck is sameas true

# TODO: remove this check very soon after the testing with all the OSs (fititnt, 2019-12-08 11:14 BRT)
#- fail:
#    msg: "testing"

- name: OpenResty
  include: openresty/main.yml
  tags:
    - alb
    - alb-openresty
  when:
    - alb_manange_all is sameas true
    - alb_manange_openresty is sameas true

- name: HAproxy
  include: haproxy/main.yml
  tags:
    - alb
    - alb-haproxy
  when:
    - alb_manange_all is sameas true
    - alb_manange_haproxy is sameas true

- name: ALB rule for each Sysapp
  include: sysapps/sysapps.yml
  tags:
    - alb
    - alb-sysapps
  when:
    - alb_manange_all is sameas true
    - alb_manange_sysapps is sameas true

- name: ALB rule for each App
  include: apps/apps.yml
  tags:
    - alb
    - alb-apps
  when:
    - alb_manange_all is sameas true
    - alb_manange_apps is sameas true

- name: logrotate/logrotate.yml
  include: logrotate/logrotate.yml
  tags:
    - alb
    - alb-logrotate
  when:
    - alb_manange_all is sameas true
    - alb_manange_logrotate is sameas true

- name: ufw/main.yml
  include: ufw/main.yml
  tags:
    - alb
    - alb-ufw
    - alb-firewall
  when:
    - alb_manange_all is sameas true
    - alb_manange_ufw is sameas true

- name: status/main.yml
  include: status/main.yml
  tags:
    - always
    - alb
    - alb-status
    - alb-status-final

## Goodbye _____________________________________________________________________

- name: "/etc/ansible/facts.d/alb_lastrun.fact (Only alb_manange_sanitycheck: yes /  alb_manange_sanitycheck: yes will not deploy this fact)"
  template:
    src: files/alb_lastrun.fact
    dest: /etc/ansible/facts.d/alb_lastrun.fact
    mode: 0755
  changed_when: false
  tags:
    - always
  when: (alb_manange_haproxy is sameas true) or (alb_manange_openresty is sameas true) or (alb_manange_ufw is sameas true) or (alb_manange_common is sameas true) or (alb_manange_apps is sameas true) or (alb_manange_logrotate is sameas true) 
