---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

- name: "AP-ALB | Welcome message"
  debug:
    msg:
      alb_version: "{{ alb_version }}"
      node:
        os: "{{ ansible_os_family | default('undefined') | lower }}"
        dist: "{{ ansible_distribution | default('undefined') | lower }}"
        dist_major_ver: "{{ ansible_distribution_major_version | default('undefined') | lower }}"
  tags:
    - alb
    - always

## Variable loading based on node Operational System ___________________________
- name: "AP-ALB | OS Family variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_osfamily is defined) | ternary(alb_vars_osfamily, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/{{ ansible_os_family | default('undefined') | lower }}.yml"
    - "os-family/{{ (ansible_os_family is defined) | ternary('untested','unknown') }}.yml"
  tags:
    - alb
    - always

- name: "AP-ALB | OS Family version variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_osfamilyversion is defined) | ternary(alb_vars_osfamilyversion, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/os-family-version/{{ ansible_os_family | default('undefined') | lower }}-{{ ansible_distribution_major_version | default('undefined') | lower }}.yml"
    - "os-family/os-family-version/no-os-family-version-customization.yml"
  tags:
    - alb
    - always

- name: "AP-ALB | Distribution variables (may override OS Family variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_distribution is defined) | ternary(alb_vars_distribution, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/{{ ansible_distribution | default('undefined') | lower }}.yml"
    - "os-family/distribution/no-os-family-customization.yml"
  tags:
    - alb
    - always

- name: "AP-ALB | Specific version distribution variables (may override OS Family and Distribution variables, if exist)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (alb_vars_distribution_version is defined) | ternary(alb_vars_distribution_version, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/distribution/version/{{ ansible_distribution | default('undefined') | lower }}-{{ ansible_distribution_major_version | default('undefined') | lower }}.yml"
    - "os-family/distribution/version/no-distribution-customization.yml"
  tags:
    - alb
    - always

## Run each ALB subcomponent ___________________________________________________

- name: "bootstrap/main.yml"
  include: bootstrap/main.yml
  tags:
    - alb
    - alb-bootstrap
  when:
    - alb_manange_all is sameas true
    - alb_manange_bootstrap is sameas true

- name: "AP-ALB | Abort if running in Unknow state"
  fail:
    msg: "{{ alb_internal_alert_critical_all }}"
  tags:
    - always
  when:
    - alb_internal_alert_critical_all is defined

- name: "ALB: check the version of last run on /etc/ansible/facts.d/alb_lastrun.fact (main)"
  set_fact:
    alb_version_lastrun: "{{ ansible_facts['ansible_local']['alb_lastrun']['alb_version'] }}"
  tags:
    - always
  when:
    - ansible_facts['ansible_local'] is defined and ansible_facts['ansible_local']['alb_lastrun'] is defined and ansible_facts['ansible_local']['alb_lastrun']['alb_version'] is defined
    - alb_version_lastrun|int != -1

- name: "AP-ALB | ALB/SanityCheck"
  include: sanitycheck/main.yml
  tags:
    - alb
    - alb-sanitycheck
  when:
    - alb_manange_all is sameas true
    - alb_manange_sanitycheck is sameas true

- name: "AP-ALB | ALB/OpenResty"
  include: openresty/main.yml
  tags:
    - alb
    - alb-openresty
  when:
    - alb_manange_all is sameas true
    - alb_manange_openresty is sameas true

- name: "AP-ALB | ALB/HAproxy"
  include: haproxy/main.yml
  tags:
    - alb
    - alb-haproxy
  when:
    - alb_manange_all is sameas true
    - alb_manange_haproxy is sameas true

- name: "AP-ALB | ALB/Sysapps"
  include: sysapps/main.yml
  tags:
    - alb
    - alb-sysapps
  when:
    - alb_manange_all is sameas true
    - alb_manange_sysapps is sameas true

- name: "AP-ALB | ALB/Apps"
  include: apps/main.yml
  tags:
    - alb
    - alb-apps
  when:
    - alb_manange_all is sameas true
    - alb_manange_apps is sameas true

- name: "AP-ALB | ALB/Logrotate"
  include: logrotate/logrotate.yml
  tags:
    - alb
    - alb-logrotate
  when:
    - alb_manange_all is sameas true
    - alb_manange_logrotate is sameas true

- name: "AP-ALB | ALB/UFW"
  include: ufw/main.yml
  tags:
    - alb
    - alb-ufw
    - alb-firewall
  when:
    - alb_manange_all is sameas true
    - alb_manange_ufw is sameas true

- name: "AP-ALB | ALB/Status"
  include: status/main.yml
  tags:
    #- always
    - alb
    - alb-status
    - alb-status-final

## Goodbye _____________________________________________________________________

- name: "/etc/ansible/facts.d/alb_lastrun.fact (Only alb_manange_sanitycheck: yes /  alb_manange_sanitycheck: yes will not deploy this fact)"
  template:
    src: files/alb_lastrun.fact
    dest: /etc/ansible/facts.d/alb_lastrun.fact
    mode: 0755
  changed_when: false
  tags:
    - always
  when: (alb_manange_haproxy is sameas true) or (alb_manange_openresty is sameas true) or (alb_manange_ufw is sameas true) or (alb_manange_common is sameas true) or (alb_manange_apps is sameas true) or (alb_manange_logrotate is sameas true)
