---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

# @see https://docs.ansible.com/ansible/latest/modules/apt_module.html

- name: Instalação de OpenResty, Lua Rest & Lua Resty AutoSSL (faz o HTTPS para os Apps)
  include: openresty-luarocks-lua-resty-auto-ssl-install.yml
  tags:
  - alb
  - alb-openresty

# TODO: break default-files.yml in multiple files (fititnt, 2019-08-04 01:34 BRT)
- name: Arquivos padrões do OpenResty
  include: default-files.yml
  tags:
  - alb
  - alb-openresty

- name: ALB rule for each App
  include: apps.yml
  tags:
  - alb
  - alb-app

# ansible-playbook -i hosts mnemosine.yml --skip-tags "alb-openresty,alb-app"
- name: HAproxy
  include: haproxy.yml
  tags:
  - alb
  - alb-haproxy
  when: application_load_balancer_forceignore_haproxy is defined and application_load_balancer_forceignore_haproxy != true

#- name: Sites HTML estático
#  include: sites-static.yml
#  tags:
#  - serverblocksetup

#- name: Sites HTML estático
#  import_tasks: site-static.yml
#  #loop: "{{ openrestyautossl_sites_static | dict2items }}"
#  tags:
#  - serverblocksetup