---
# FILE:            {{ role_path }}/tasks/haproxy/install/apt.yml
# LICENSE:         Public Domain

# TODO: improve this hardcoded version (fititnt, 2019-12-11 04:54 BRT)
- name: "haproxy | install | apt.yml (Debian Family)"
  apt:
    name: 'haproxy=2.0.*'
    state: 'present'
#  when:
#    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
#    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"