---
# FILE:            {{ role_path }}/tasks/haproxy/haproxy.yml
# LICENSE:         Public Domain

# TODO: make choosable via variables the HAProxy version and the
#       repository, see https://haproxy.debian.net.

# ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-haproxy" "alb_forceredeploy=yes"
# /usr/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg

# TODO: fix issue with at very first time HAProxy is not started after installation (fititnt, 2019-11-04 20:40 BRT)

# https://haproxy.debian.net/#?distribution=Ubuntu&release=bionic&version=2.0

# - name: "haproxy (Debian/Ubuntu) | add-apt-repository ppa:vbernat/haproxy-2.0"
#   apt_repository:
#     repo: ppa:vbernat/haproxy-2.0
#     update_cache: yes
#   when:
#    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
#    - "alb_manange_haproxy_repository is defined and alb_manange_haproxy_repository|bool"

- name: 'haproxy (Debian/Ubuntu) | apt-get install haproxy=2.0.\*'
  apt:
    name: 'haproxy=2.0.*'
    state: 'present'
  when:
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"

# - name: "haproxy (CentOS/RHEL) | Install HAProxy"
#   dnf:
#     name: "haproxy"
#     state: present
#   when:
#     - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

- name: "haproxy (CentOS/RHEL) | Install HAProxy"
  package:
    name: haproxy
    state: present
  when:
   - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

- name: "haproxy (CentOS/RHEL) | Install HAProxy"
  yum:
    name: haproxy
    # state: present
    state: latest
  when:
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"

- name: "haproxy (CentOS/RHEL) | Ensure HAProxy is installed"
  package: name=haproxy state=present
  when:
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"

# Os comandos anteriores não esta instalando haproxy, mesmo ele ja existindo (1.8, não repo externo)
- name: "haproxy (CentOS/RHEL) | HOTFIX, sudo dnf install haproxy -y (TODO: remove this shell command) "
  shell: "sudo dnf install haproxy -y"
  when:
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"
