---

- name: "handlers | reload haproxy (block)"
  block:
    - name: "handlers | reload haproxy"
      service:
        name: haproxy
        state: restarted
  rescue:
    - name: "handlers | reload haproxy | shell: /usr/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg"
      shell: "/usr/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg"
      register: syntax_check_haproxy
    - name: "handlers | reload haproxy | output: /usr/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg"
      debug:
        msg: "{{ syntax_check_haproxy }}"