---
# FILE:            {{ role_path }}/tasks/openresty/install/storage-adapters/consul.yml
# LICENSE:         Public Domain

# Message for who does not read documentation, but is reading the sources
- name: "openresty | install | storage-adapters | consul.yml: opm get hamishforbes/lua-resty-consul"
  shell: opm get hamishforbes/lua-resty-consul
  args:
    warn: false
  tags:
    - skip_ansible_lint

- name: "openresty | install | storage-adapters | consul.yml: | MONKEYPATCH | resty/auto-ssl/storage_adapters/consul.lua
        (untill resty-auto-ssl include this storage driver)"
  template:
    src: "files/resty/auto-ssl/storage_adapters/consul.lua"
    dest: /usr/local/share/lua/5.1/resty/auto-ssl/storage_adapters/consul.lua
  notify:
    - reload openresty
