---
# FILE:            {{ role_path }}/tasks/openresty/install/storage-adapters/main.yml
# LICENSE:         Public Domain

- name: "openresty | install | storage-adapters | main.yml: consul.yml"
  include: "{{ role_path }}/tasks/openresty/install/storage-adapters/consul.yml"
  when:
    - "(alb_internal_node_storage_driver is defined) and (alb_internal_node_storage_driver == 'consul')"
    # - "(alb_use_consul is defined) and (alb_use_consul|bool)"
