---
# FILE:            {{ role_path }}/tasks/devtools/devtools.yml
# LICENSE:         Public Domain

# Requires: `alb_manange_devtools: yes` variable
# To only apply this in a play: `--tags alb-devtools`
# To only skip this in a play: `--skip-tags alb-ufw`


#- name: "devtools | devtools.yml"
#  debug:
#    msg: "devtools.yml"

- name: /etc/ansible/facts.d/alb_devtools.fact
  template:
    src: files/alb_devtools.fact
    dest: /etc/ansible/facts.d/alb_devtools.fact
    mode: 0755
  register: alb_devtools_facts_deployed

- name: devtools | Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: devtools | sudo apt-get install net-tools (for netstat)
  apt:
    name: net-tools
    state: present
  when:
    - alb_devtools_facts_deployed is changed

- name: devtools | sudo apt-get install htop
  apt:
   name: htop
   state: present
  when:
    - alb_devtools_facts_deployed is changed

- name: devtools | sudo apt-get install multitail
  apt:
   name: multitail
   state: present
  when:
    - alb_devtools_facts_deployed is changed

# @see http://feurix.org/projects/hatop/
- name: "devtools | sudo apt-get install hatop [Run with 'hatop -s /run/haproxy/admin.sock']"
  apt:
   name: hatop
   state: present
  when:
    - alb_manange_haproxy is sameas true
    - alb_devtools_facts_deployed is changed

# https://github.com/nicolargo/glances (version on master: Glances 3.1.0, default on Ubuntu 18 is a bit outdated)
# sudo apt install glances
# glances --version
# Glances v2.11.1 with psutil v5.4.2

# @TODO: consider ngxtop https://www.tecmint.com/ngxtop-monitor-nginx-log-files-in-real-time-in-linux/
#        (fititnt, 2019-11-11 22:18 BRT)
