#!/bin/sh
# FILE:            /opt/alb/bin/alb-cli-issues
# LICENSE:         Public Domain
#
# DESCRIPTION:
#
# USAGE:           Logged on the node, use
#                      /opt/alb/bin/alb-cli-issues
#                  From your control machine, hosts.yml as inventory
#                      ansible all -i hosts.yml -m raw -a "/opt/alb/bin/alb-cli-issues"
#                      ansible all -i hosts.yml --user=root -m raw -a "/opt/alb/bin/alb-cli-issues"


ALB_CLI_RESULT=0
ALB_BIN_OPENRESTY=/usr/bin/openresty
ALB_BIN_HAPROXY=/usr/sbin/haproxy
# ALB_BIN_HAPROXY=/usr/local/sbin/haproxy


# https://www.shellscript.sh/functions.html
open_ports()
{
  echo "Open Ports"
  if ! [ -x "$(command -v sockstat)" ]; then
    netstat -ntulp
  else
    sockstat -4l
  fi
}


if test -f "$ALB_BIN_OPENRESTY"; then
  # echo "$ALB_BIN_OPENRESTY exist"
  echo "\nopenresty -t"
  $ALB_BIN_OPENRESTY -t
  # syntax_check_openresty=$($openresty -t)
  if [ $? -eq 0 ]
  then
    echo "OpenResty +OK"
  else
    echo "OpenResty -NOK"
    ALB_CLI_RESULT=1
  fi

  # service openresty status

  # if ! [ -x "$(command -v systemctl)" ]; then
  #   service openresty status
  # else
  #   systemctl status openresty
  # fi

else
  echo "$ALB_BIN_OPENRESTY does not exist. Ignoring"
fi

if test -f "$ALB_BIN_HAPROXY"; then
  # echo "$ALB_BIN_HAPROXY exist"
  echo "\n$ALB_BIN_HAPROXY -c -V -f /etc/haproxy/haproxy.cfg"
  # syntax_check_haproxy=$($ALB_BIN_HAPROXY -c -V -f /etc/haproxy/haproxy.cfg)
  $ALB_BIN_HAPROXY -c -V -f /etc/haproxy/haproxy.cfg
  if [ $? -eq 0 ]
  then
    echo "HAProxy +OK"
  else
    $ALB_BIN_HAPROXY -v
    service
    echo ""
    echo "HAProxy -NOK"
    ALB_CLI_RESULT=1
  fi

  # service haproxy status

  # if ! [ -x "$(command -v systemctl)" ]; then
  #   service haproxy status
  # else
  #   systemctl status haproxy
  # fi

else
  echo "$ALB_BIN_HAPROXY does not exist. Ignoring"
fi


if [ $ALB_CLI_RESULT -eq 0 ]
then
  echo ""
  echo "AP-ALB +OK"
else
  $ALB_BIN_OPENRESTY --version
  open_ports
  echo ""
  echo "AP-ALB -NOK"
  ALB_CLI_RESULT=1
fi

#echo "result $RESULT"

exit $ALB_CLI_RESULT
