---

# FILE:            {{ role_path }}/tasks/apps/alb/openresty-conf.yml
# LICENSE:         Public Domain

- name: "openresty | apps | alb | openresty-conf.yml: /opt/alb/apps/[item.app_uid].conf"
  template:
    # src: "{{ item.vhost_template|default(alb_apps_serverblock_template) }}"
    src: "{{ alb_nginx_alb_stragies_folder }}/{{ item.app_alb_strategy }}.conf.j2"
    dest: "/opt/alb/apps/{{ item.app_uid }}.conf"
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_nginx_user }}"
    mode: 0644
    backup: yes
  with_items: "{{ alb_internal_apps }}"
  vars:
    type_of_app: "app"
    basic_auth_enabled: "{{ item.app_auth_basic_enabled | default(alb_apps__app_auth_basic_enabled) }}"
    auth_basic: '"{{ item.app_auth_basic | default(alb_apps__app_auth_basic) }}"'
    auth_basic_user_file: '"{{ item.app_auth_basic_user_file | default(alb_apps__app_auth_basic_user_file) }}"'
  when:
    - item.app_alb_strategy is defined
    - alb_internal_apps is defined and alb_internal_apps[0] is defined
    - "(alb_run_only_app_uid is not defined) or (alb_run_only_app_uid == item.app_uid)"
    - "(alb_apps_facts_deployed is changed) or (alb_forceredeploy|bool)"
  register: result_apps_rules
  notify:
    - "reload openresty"
    - "info alb component apps"
