---
# FILE:            {{ role_path }}/tasks/openresty/storage-adapters/main.yml
# LICENSE:         Public Domain

- name: "openresty | install | main.yml: choose method"
  include: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/openresty/install/package-manager/{{ alb_internal_package_manager_group | default('undefined')  }}.yml"
    - "{{ role_path }}/tasks/openresty/install/package-manager/generic.yml"

- name: "openresty | install | main.yml: storage-adapters/main.yml"
  include: "{{ role_path }}/tasks/openresty/install/storage-adapters/main.yml"

- name: "openresty | install | main.yml: default-files.yml"
  include: "{{ role_path }}/tasks/openresty/install/default-files.yml"
