---
# FILE:            {{ role_path }}/tasks/openresty/install/default-files.yml
# LICENSE:         Public Domain

- name: "openresty | resty-auto-ssl: sudo luarocks install lua-resty-auto-ssl"
  shell: "luarocks install lua-resty-auto-ssl"
  register: is_restyautossl2
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  # when: is_luarocks is failed

# TODO: trocar comando seguinte de 'shell' para 'lineinfile' ou 'template' fititnt, 2019-07-01 06:33 BRT)
# @see https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
- name: "openresty (Debian/Ubuntu) | hotfix 'err: Can't load ./.rnd into RNG', https://github.com/openssl/openssl/issues/7754#issuecomment-444063355"
  shell: "sed -i '/RANDFILE/s/^/#/g' /etc/ssl/openssl.cnf"
  become: yes
  register: is_restyautossl_hotfix_openssl
  ignore_errors: true
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  #when:
  #  - is_luarocks is failed
  #  - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: "openresty | sudo openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt"
  shell: openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt
  become: yes
  # register: is_restyautossl_fallbackkey
  # when: is_luarocks is failed
  #when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir

# TODO: resolver problema de fallbackkey não estar sendo criada automaticamente (fititnt, 2019-07-03 23:34 BRT)