---

- name: logrotate | /etc/logrotate.d/alb
  template:
    src: "{{ alb_logrotate_template_alb }}"
    dest: /etc/logrotate.d/alb
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: logrotate | /etc/logrotate.d/alb_apps
  template:
    src: "{{ alb_logrotate_template_alb_apps }}"
    dest: /etc/logrotate.d/alb_apps
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: logrotate | /etc/logrotate.d/alb_sysapps
  template:
    src: "{{ alb_logrotate_template_alb_sysapps }}"
    dest: /etc/logrotate.d/alb_sysapps
    owner: root
    group: root
    mode: '0644'
    backup: no
