---

# FILE:            {{ role_path }}/tasks/common/common.yml
# LICENSE:         Public Domain

# Requires: `alb_manange_common: yes` variable
# To only apply this in a play: `--tags alb-common`
# To only skip this in a play: `--skip-tags alb-common`

# @TODO: consider implementing changes to allow Mitogen,
#        @see https://www.toptechskills.com/ansible-tutorials-courses/speed-up-ansible-playbooks-pipelining-mitogen/
#        (fititnt, 2019-11-11 21:56 BRT)

#- debug:
#    msg: "ansible_facts.packages {{ ansible_facts.packages }}"
#    msg: "ansible_facts.packages {{ ansible_facts.packages }}"

#- name: common | mkdir -p /etc/ansible/facts.d/
#  file:
#    path: /etc/ansible/facts.d/
#    state: directory
#    owner: root
#    group: root
#    mode: 0755
#    recurse: true

#- name: /etc/ansible/facts.d/alb_common.fact
#  template:
#    src: files/alb_common.fact
#    dest: /etc/ansible/facts.d/alb_common.fact
#    mode: 0755
#  register: alb_common_facts_deployed

# > AP-ALB v0.8.x adaptations to support RHEL/CentOS 8 family and design changes to allow flexibility even for non-tested OSs #34
#  - Variables via type of OS 
#    - https://docs.ansible.com/ansible/latest/modules/include_vars_module.html
#    - https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/variables/
#  - ansible_pkg_mgr strategy, see
#    - https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/installing_packages/
#    - https://github.com/openstack/openstack-ansible-galera_server/blob/master/tasks/galera_install.yml

- name: "common (Debian/Ubuntu) | sudo apt install -y aptitude"
  apt:
    name: aptitude
    state: present
  when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: "common (CentOS/RHEL) | sudo dnf install -y epel-release yum-utils"
  dnf:
    name:
      - epel-release
      - yum-utils
    state: present
  when: "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

- name: "common | hostname = inventory_hostname"
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname_short != ansible_hostname

- name: "common | [Padronize the Timezone as UTC] sudo timedatectl set-timezone UTC"
  timezone:
    name: UTC
  when: ansible_facts['date_time']['tz'] != 'UTC'

- name: common | mkdir -p /etc/ansible/facts.d/
  file:
    path: /etc/ansible/facts.d/
    state: directory
    #owner: root
    #group: root
    #mode: 0755
    #recurse: true

#- name: common | sudo apt-get install software-properties-common
#  apt:
#    name: "software-properties-common"
  # when: "'software-properties-common' not in ansible_facts.packages"