---

# FILE:            {{ role_path }}/tasks/common/common.yml
# LICENSE:         Public Domain

# Requires: `alb_manange_common: yes` variable
# To only apply this in a play: `--tags alb-common`
# To only skip this in a play: `--skip-tags alb-common`

# @TODO: consider implementing changes to allow Mitogen,
#        @see https://www.toptechskills.com/ansible-tutorials-courses/speed-up-ansible-playbooks-pipelining-mitogen/
#        (fititnt, 2019-11-11 21:56 BRT)

- name: "[Ansible likes aptitude over apt-get] sudo apt-get install aptitude"
  apt:
   name: aptitude
   state: present

- name: "[Padronize the hostname] sudo hostnamectl set-hostname {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname_short != ansible_hostname

- name: "[Padronize the hostname] sudo hostnamectl set-hostname {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname_short != ansible_hostname

- name: "[Padronize the Timezone as UTC] sudo timedatectl set-timezone UTC"
  timezone:
    name: UTC
  when: ansible_facts['date_time']['tz'] != 'UTC'

#- name: sudo apt-get install software-properties-common
#  apt:
#    name: "software-properties-common"