---

# FILE:            {{ role_path }}/status/main.yml
# LICENSE:         Public Domain


# TODO: move to end of this list
- name: "installed-packages.yml"
  include: installed-packages.yml
  tags:
    - alb-status-alb
    - alb-status-installed-packages

# TODO: move to end of this list
- name: "available-packages.yml"
  include: available-packages.yml
  tags:
    - alb-status-alb
    - alb-status-available-packages

- name: "network.yml"
  include: network.yml
  tags:
    - alb-status-alb-minimal
    - alb-status-basic

- name: "filesystem.yml"
  include: filesystem.yml
  tags:
    - alb-status-alb-minimal
    - alb-status-basic

- name: "alb-node.yml"
  include: alb-node.yml
  tags:
    - alb-status-alb
    - alb-status-alb-node

- name: "alb-cluster.yml"
  include: alb-cluster.yml
  tags:
    - alb-status-alb
    - alb-status-alb-cluster
    - never
