---

# FILE:            {{ role_path }}/status/network.yml
# LICENSE:         Public Domain

- name: "status | main.yml: open ports (local), detect"
  command: "{{ alb_internal_status_localports }}"
  become: yes
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: alb_status_netstat
  when:
    - "alb_internal_status_localports is defined and alb_internal_status_localports"

- name: "status | main.yml: open ports (local), print"
  debug:
    msg:
      stdout_lines: "{{ alb_status_netstat.stdout_lines | default('undefined') }}"
      stderr_lines: "{{ alb_status_netstat.stderr_lines | default('undefined') }}"
  when:
    - "alb_internal_status_localports is defined and alb_internal_status_localports"
