---
# LICENSE:         Public Domain

# https://openresty.org/en/linux-packages.html

## apt install -y openresty ____________________________________________________

- name: "openresty (Debian/Ubuntu) | OpenResty apt-key"
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
  when:
    - is_openresty is failed
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
    - "alb_manange_openresty_repository is defined and alb_manange_openresty_repository|bool"

- name: "openresty (Debian/Ubuntu) | OpenResty Repository"
  apt_repository:
    repo: 'deb http://openresty.org/package/ubuntu bionic main' 
    state: present
    filename: openresty
    update_cache: yes
  when:
    - is_openresty is failed
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
    - "alb_manange_openresty_repository is defined and alb_manange_openresty_repository|bool"

# TODO: remove this task when https://openresty.org/en/linux-packages.html already
#       have repository for CentOS/RHEL 8 (fititnt, 2019-12-06 20:04)
- name: "openresty (CentOS/RHEL) | OpenResty Repository (force use CentOS/RHEL 7 Untill OpenResty officialy release support for 8)"
  yum_repository:
    name: "openresty"
    description: "Official OpenResty Open Source Repository for CentOS"
    # baseurl: 'https://openresty.org/package/centos/$releasever/$basearch' # This original line
    baseurl: 'https://openresty.org/package/centos/7/$basearch'
    skip_if_unavailable: false
    gpgcheck: true
    repo_gpgcheck: false
    gpgkey: 'https://openresty.org/package/pubkey.gpg'
    state: present
    enabled: true
  when:
    - is_openresty is failed
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
    - "alb_manange_openresty_repository is defined and alb_manange_openresty_repository|bool"

- debug:
    msg: "{{ ansible_distribution_major_version }}"

# TODO: remove this task when https://openresty.org/en/linux-packages.html already
#       have repository for CentOS/RHEL 8 (fititnt, 2019-12-06 20:04)
# - name: "openresty (CentOS/RHEL) | MONKEYPATCH | OpenResty Repository (force use CentOS/RHEL 7 Untill OpenResty officialy release support for 8)"
#   shell: sed -i '/RANDFILE/s/^/#/g' /etc/yum.repos.d/openresty.repo
#   # replace:
#   #   path: /etc/yum.repos.d/openresty.repo
#   #   regexp: '(\$releasever)'
#   #   replace: '7'
#   when:
#     - is_openresty is failed
#     - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
#     - "alb_manange_openresty_repository is defined and alb_manange_openresty_repository|bool"
#     - "ansible_distribution_major_version == ''"

- name: "openresty (Debian/Ubuntu) | Install OpenResty"
  apt:
    name: openresty
    state: present
    update_cache: yes
  when:
    - is_openresty is failed
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: "openresty (CentOS/RHEL) | Install OpenResty"
  dnf:
    name: "openresty"
    state: present
  when:
    - is_openresty is failed
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

# executado manualmente
#    sudo yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo

## apt install -y luarocks _____________________________________________________
- name: "openresty (Debian/Ubuntu) | luarocks: apt install -y luarocks"
  apt:
    name: luarocks
    state: present
    update_cache: yes
  when:
    - is_luarocks is failed
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: "openresty (CentOS/RHEL) | luarocks: dnf install -y openresty-opm"
  dnf:
    name: "openresty-opm"
    state: present
  when:
    - is_openresty is failed
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

- name: "openresty (CentOS/RHEL) | luarocks: dnf install -y luarocks"
  dnf:
    name: "luarocks"
    state: present
  when:
    - is_openresty is failed
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"

## apt install -y luarocks _____________________________________________________

# TODO: manage better if already installed
#- name: "openresty | opm list | grep lua-resty-consul | wc -l?  (Safe to ignore error first time!)"
#  shell: opm list | grep lua-resty-consul | wc -l
#  register: is_lua_resty_consul
#  changed_when: false
#  ignore_errors: true

- name: "openresty | opm get hamishforbes/lua-resty-consul"
  shell: opm get hamishforbes/lua-resty-consul
  when: 
    - alb_use_consul|bool

- name: openresty | MONKEYPATCH | resty/auto-ssl/storage_adapters/consul.lua (untill resty-auto-ssl include this storage driver)
  template:
    # src: "{{ role_path }}/templates/openresty/nginx/conf/nginx.conf.j2"
    src: "files/resty/auto-ssl/storage_adapters/consul.lua"
    dest: /usr/local/share/lua/5.1/resty/auto-ssl/storage_adapters/consul.lua
  when:
    - "alb_use_consul is defined and alb_use_consul|bool"
  notify:
    - reload openresty

## luarocks install lua-resty-auto-ssl _________________________________________
# @see https://github.com/GUI/lua-resty-auto-ssl#installation

- name: "openresty | sudo mkdir /etc/resty-auto-ssl ; sudo chown {{ alb_nginx_user }} /etc/resty-auto-ssl"
  file:
    state: directory
    path: /etc/resty-auto-ssl
    owner: "{{ alb_nginx_user }}"
    group: "{{ alb_nginx_user }}"
  when: is_luarocks is failed

- name: "openresty | resty-auto-ssl: sudo luarocks install lua-resty-auto-ssl"
  shell: luarocks install lua-resty-auto-ssl
  register: is_restyautossl2
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  when: is_luarocks is failed

# TODO: trocar comando seguinte de 'shell' para 'lineinfile' ou 'template' fititnt, 2019-07-01 06:33 BRT)
# @see https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
- name: "openresty (Debian/Ubuntu) | hotfix 'err: Can't load ./.rnd into RNG', https://github.com/openssl/openssl/issues/7754#issuecomment-444063355"
  shell: sed -i '/RANDFILE/s/^/#/g' /etc/ssl/openssl.cnf
  register: is_restyautossl_hotfix_openssl
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  when:
    - is_luarocks is failed
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: "openresty | sudo openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt"
  shell: openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt
  become: yes
  register: is_restyautossl_fallbackkey
  when: is_luarocks is failed
  #when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir

# TODO: resolver problema de fallbackkey não estar sendo criada automaticamente (fititnt, 2019-07-03 23:34 BRT)
    