---
# FILE:            {{ role_path }}/tasks/haproxy/management/errorfiles.yml
# LICENSE:         Public Domain

# TODO: maybe move this directory creation to install part (fititnt, 2019-12-11 06:59 BRT)
- name: "haproxy | management | errorfiles.yml: /etc/haproxy/errors/"
  file:
    path: /etc/haproxy/errors/
    state: directory
    recurse: yes

- name: "haproxy | management | errorfiles.yml"
  copy:
    src: "{{ alb_haproxy_errors_folder }}"
    dest: /etc/haproxy/errors/
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_internal_root_group }}"
    mode: '0644'