---
# FILE:            {{ role_path }}/tasks/haproxy/management/systemd.yml
# LICENSE:         Public Domain

- name: "haproxy | management | systemd.yml: {{ alb_internal_haproxy_conf }}"
  template:
    # src: "{{ role_path }}/templates/openresty/nginx/conf/nginx.conf.j2"
    src: "{{ alb_haproxy_haproxy_template }}"
    dest: "{{ alb_internal_haproxy_conf }}"
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_internal_root_group }}"
    mode: '0644'
    backup: yes
  notify:
    - reload haproxy

# Enabled/Started must be AFTER moving new /etc/haproxy/haproxy.cfg
# configurations or Ansible will not be able to update one new valid
# configuration if old one was already with error. By moving this step
# after we avoid user being forced to solve manually on the server 
- name: "haproxy | reconfigure: sudo systemctl enable haproxy.service"
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: "haproxy | reconfigure: facts"
  debug:
    msg: "{{ alb_haproxy_facts }}"