---

# FILE:            {{ role_path }}/tasks/sysapps.yml
# LICENSE:         Public Domain

# ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-sysapps" --extra-vars "alb_forceredeploy=yes"

## NGinx Server Blocks (e.g. ~Apache Virtual Hosts)
#- name: "NGinx Server Blocks (e.g. ~Apache Virtual Hosts)"
#  template:
#    src: "{{ item.vhost_template|default(alb_sysapps_serverblock_template) }}"
#    dest: "/usr/local/openresty/nginx/conf/sites-enabled/{{ item.domain }}.conf"
#    owner: root
#    group: "root"
#    mode: 0644
#    backup: yes
#  with_items: "{{ alb_sysapps }}"
#  notify: reload openresty

- name: /etc/ansible/facts.d/alb_sysapps.fact
  template:
    src: files/alb_sysapps.fact
    dest: /etc/ansible/facts.d/alb_sysapps.fact
    mode: 0755
  register: alb_sysapps_facts_deployed

- name: " sysapps | /opt/alb/sysapps/.htaccess"
  htpasswd:
    path: /opt/alb/sysapps/.htaccess
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state | default('present') }}"
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_nginx_user }}"
    mode: 0650
  with_items: "{{ alb_sysapps_htpassword }}"
  no_log: true
  when:
    - alb_sysapps is defined and alb_sysapps[0] is defined
    - alb_sysapps_htpassword is defined and alb_sysapps_htpassword[0] is defined
    - "(alb_sysapps_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "sysapps | ALB Sysapp Rules"
  template:
    # src: "{{ item.vhost_template|default(alb_sysapps_serverblock_template) }}"
    # src: "{{ role_path }}/templates/alb-strategy/{{ item.app_alb_strategy | default(alb_default_app_alb_strategy) }}.conf.j2"
    src: "{{ alb_nginx_alb_stragies_folder }}/{{ item.app_alb_strategy }}.conf.j2"
    dest: "/opt/alb/sysapps/{{ item.app_uid }}.conf"
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_nginx_user }}"
    mode: 0644
    backup: yes
  with_items: "{{ alb_sysapps }}"
  vars:
    type_of_app: "sysapp"
    basic_auth_enabled: "{{ item.app_auth_basic_enabled | default(alb_sysapps__app_auth_basic_enabled) }}"
    auth_basic: '"{{ item.app_auth_basic | default(alb_sysapps__app_auth_basic) }}"'
    auth_basic_user_file: '"{{ item.app_auth_basic_user_file | default(alb_sysapps__app_auth_basic_user_file) }}"'
  when:
    - alb_sysapps is defined and alb_sysapps[0] is defined
    - "(alb_sysapps_facts_deployed is changed) or (alb_forceredeploy|bool)"
  notify: reload openresty

- name: sysapps | mkdir /var/log/sysapp/[app_uid]
  file:
    path: /var/log/sysapp/{{ item.app_uid }}
    state: directory
    mode: '0644'
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_nginx_user }}"
  with_items: "{{ alb_sysapps }}"
  when:
    - alb_sysapps is defined and alb_sysapps[0] is defined
    - "(alb_sysapps_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: sysapps | mkdir /var/log/sysapp/[app_uid]/access.log
  file:
    path: /var/log/sysapp/{{ item.app_uid }}/access.log
    state: touch
    mode: '0644'
    owner: "{{ alb_nginx_user }}"
    group: "{{ alb_nginx_user }}"
  with_items: "{{ alb_sysapps }}"
  when:
    - alb_sysapps is defined and alb_sysapps[0] is defined
    - "(alb_sysapps_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: sysapps | mkdir /var/log/sysapp/[app_uid]/error.log
  file:
    path: /var/log/sysapp/{{ item.app_uid }}/error.log
    state: touch
    mode: '0644'
    owner: "{{ alb_nginx_user }}"
    group: "{{ alb_nginx_user }}"
  with_items: "{{ alb_sysapps }}"
  when:
    - alb_sysapps is defined and alb_sysapps[0] is defined
    - "(alb_sysapps_facts_deployed is changed) or (alb_forceredeploy|bool)"
