---
# FILE:            {{ role_path }}/tasks/openresty/check-initial-state.yml
# LICENSE:         Public Domain

# TODO: implement this file in the default run on main.yml

## openresty? luarocks? lua-resty-auto-ssl? ____________________________________
- name: "openresty | check-initial-state.yml: openresty? (Safe to ignore error first time!)"
  shell: openresty -v
  register: is_openresty
  changed_when: false
  ignore_errors: true

- name: "openresty | check-initial-state.yml: luarocks?  (Safe to ignore error first time!)"
  shell: luarocks --version
  register: is_luarocks
  changed_when: false
  ignore_errors: true

- name: "openresty | check-initial-state.yml: lua-resty-auto-ssl?  (Safe to ignore error first time!)"
  stat:
    path: /etc/resty-auto-ssl
  register: is_restyautossl
  #register: restyautossl_folder