---
# FILE:            {{ role_path }}/tasks/openresty/main.yml
# LICENSE:         Public Domain

- name: "openresty | main.yml: /etc/ansible/facts.d/alb_openresty.fact"
  template:
    src: files/alb_openresty.fact
    dest: /etc/ansible/facts.d/alb_openresty.fact
  register: alb_openresty_facts_deployed

- name: "openresty | main.yml: install/main.yml"
  include: "{{ role_path }}/tasks/openresty/install/main.yml"
  #when:
  #  - "(alb_openresty_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "openresty | main.yml: install/management.yml"
  include: "{{ role_path }}/tasks/openresty/install/main.yml"
  #when:
  #  - "(alb_openresty_facts_deployed is changed) or (alb_forceredeploy|bool)"
