---
# FILE:            {{ role_path }}/tasks/haproxy/install/filesystem-structure.yml
# LICENSE:         Public Domain

- name: "haproxy | install | filesystem-structure.yml: ensure consistent diretory structure
        (/etc/haproxy, /etc/haproxy/errors/) on all OSs"
  file:
    path: /etc/haproxy/errors/
    state: directory
    recurse: yes

- name: "haproxy | install | filesystem-structure.yml: ensure consistent error files on all OSs"
  copy:
    src: "{{ alb_haproxy_errors_folder }}"
    dest: /etc/haproxy/errors/
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_internal_root_group }}"
    mode: '0644'

# Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]
- name: "haproxy | install | filesystem-structure.yml: ensure /run/haproxy/ folder already exist on all OSs
        (to allow use /run/haproxy/admin.sock)"
  file:
    path: /run/haproxy/
    state: directory
    owner: "{{ alb_internal_root_user }}"
    group: "{{ alb_internal_root_group }}"

- name: "haproxy | install | filesystem-structure.yml: extra symbolic link (FreeBSD Family)"
  file:
    src: "{{ alb_internal_haproxy_conf }}"
    dest: "{{ alb_internal_haproxy_conf_symlink }}"
    owner: "{{ alb_internal_root_user }}"
    state: link
    force: yes
  when:
    - "(alb_internal_haproxy_conf_symlink is defined) and (alb_internal_haproxy_conf_symlink)"
