---
# FILE:            {{ role_path }}/tasks/haproxy/install.yml
# LICENSE:         Public Domain

- name: "haproxy | install | generic.yml"
  package:
    name: "{{ alb_internal_haproxy_package.name }}"
    state: "{{ alb_internal_haproxy_package.state }}"
  when:
    - "(alb_internal_haproxy_package is defined) and (alb_internal_haproxy_package.name is defined)"
