---
# FILE:            {{ role_path }}/tasks/haproxy/install/apt.yml
# LICENSE:         Public Domain

# TODO: improve this hardcoded version (fititnt, 2019-12-11 04:54 BRT)
- name: "haproxy | install | yum.yml (RedHat Family)"
  yum:
    name: haproxy
    # state: present
    state: latest
  when:
    - "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"
    - "alb_manange_haproxy_install is defined and alb_manange_haproxy_install|bool"