---

- name: "sanitycheck:global | global/main.yml"
  include: global/main.yml

- name: "sanitycheck:ufw | ufw/ufw-pre-check.yml"
  include: ufw/ufw-pre-check.yml
  when:
    - "alb_manange_ufw is defined and alb_manange_ufw is sameas true"