---

# @TODO: alb_dmz_withtargets still include redundant UFW rules that should be filtered out
#        see https://jinja.palletsprojects.com/en/2.10.x/templates/#rejectattr
#        (fititnt, 2019-11-25 12:10 BRT)

- name: "ufw | allow-dmz | alb_dmz_withtargets based on alb_dmz (including duplicated, needs be fixed)"
  set_fact:
    alb_dmz_withtargets: "{{ (alb_dmz_withtargets | default([])) + [(item | combine({ 'targets': alb_dmz }))] }}"
    # alb_dmz_withtargets: "{{ (alb_dmz_withtargets | default([])) + [item | combine({ 'targets': (alb_dmz | rejectattr('ip', item.ip)) }) ] }}"
  with_items: "{{ alb_dmz }}"

- name: "ufw | allow-dmz | alb_dmz_withtargets [print value]"
  debug:
    msg: "{{ alb_dmz_withtargets }}"

- name: "ufw | allow-dmz: allow alb_dmz_withtargets"
  ufw:
    rule: "allow"
    from_ip: "{{ item.0.ip }}"
    to_ip: "{{ item.1.ip }}"
    comment: "{{ alb_ufw_commentprefix }}{{ 'DMZ ' + (item.0.name | default(item.0.ip)) }}"
  with_subelements:
    - "{{ alb_dmz_withtargets }}"
    - targets
