---

- debug:
    msg: "{{ alb_dmz }}"
- debug:
    msg: "{{ alb_dmz | list}}"

- debug:
    msg: "{{ alb_dmz + alb_dmz }}"

- name: "ufw | allow-dmz | prepare ips"
  set_fact:
    alb_dmz_allips: "{{ alb_dmz | map(attribute='ip') | list }}"

- name: "ufw | allow-dmz | alb_dmz2"
  set_fact:
    alb_dmz2: "{{ item | combine( { 'targets': item } ) }}"
  with_items: "{{ alb_dmz }}"

- debug:
    msg: "{{ alb_dmz2 }}"  

- name: "ufw | allow-dmz: FROM "
  ufw:
    rule: "{{ item[0].rule | default('allow') }}"
    from: "{{ item[0].ip }}"
    to: "{{ item[1].ip }}"
    comment: "{{ alb_ufw_commentprefix }}{{ item[0].comment | default('DMZ FROM ' + item[0].name | default(item[0].ip)) }}"
  with_subelements:
    alb_dmz
    alb_dmz
  #loop: "{{ alb_dmz }}"
  #loop_control:
  #  extended: yes
  # when: "alb_dmz is defined"

- name: "ufw | allow-dmz: TO {{ alb_dmz }}"
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    dest: "{{ item.ip | default(item) }}"
    delete: "{{ item.delete | default('no')}}"
    comment: "{{ alb_ufw_commentprefix }}{{ item.comment | default('DMZ TO ' + item.name | default(ansible_loop.index0 | string)) }}"
  loop: "{{ alb_dmz }}"
  loop_control:
    extended: yes
  when: "alb_dmz is defined"
