---


- name: "allow-superuser.yml"
  debug:
    msg: teste ufw 123 allow-superuser.yml

- name: "allow-dmz: FROM {{ alb_superusers }}"
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    from: "{{ item.ip | default(item) }}"
    comment: "{{ alb_ufw_commentprefix }}{{ item.comment | default('Superuser FROM ' + item.name | default(ansible_loop.index0 | string)) }}"
  loop: "{{ alb_superusers }}"
  loop_control:
    extended: yes
  when: "alb_superusers is defined"

- name: "allow-dmz: TO {{ alb_superusers }}"
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    dest: "{{ item.ip | default(item) }}"
    comment: "{{ alb_ufw_commentprefix }}{{ item.comment | default('Superuser TO ' + item.name | default(ansible_loop.index0 | string)) }}"
  loop: "{{ alb_dmz }}"
  loop_control:
    extended: yes
  when: "alb_superusers is defined"
