---
# tasks/ufw/main.yml

# To run this playbook alone, you can use this strategy:
#     ansible-playbook --tags="alb-haproxy" playbook.yml -i hosts
# To run this playbook alone, but ignore cached facts (like a semi-broken deploy), add alb_forceredeploy=yes:
#     ansible-playbook --tags="alb-ufw" --extra-vars "alb_forceredeploy=yes" playbook.yml -i hosts

- name: /etc/ansible/facts.d/alb_ufw.fact
  template:
    src: files/alb_ufw.fact
    dest: /etc/ansible/facts.d/alb_ufw.fact
    mode: 0755
  register: alb_ufw_facts_deployed

## ufw status verbose  (before) ________________________________________________
- name: "ufw | ufw status verbose (before)"
  shell: "ufw status verbose"
  become: "yes"
  changed_when: false
  ignore_errors: true
  register: ufw_status_verbose1
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "ufw | ufw status verbose print (before)"
  debug: var=ufw_status_verbose1.stdout_lines
  when:
    - "ufw_status_verbose1 is not failed"
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: ufw | install-ufw.yml
  include: install-ufw.yml
  when:
    - "ufw_status_verbose1 is failed"
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: ufw | ufw-reset.yml
  include: ufw-reset.yml
  when:
    - "alb_ufw_canreset is defined and alb_ufw_canreset is sameas true"
    - "alb_ufw_reset is defined and alb_ufw_canreset is sameas true"
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "ufw | Rules alb_ufw_rules_always"
  include: rules.yml
  vars:
    ufw_rules: "{{ alb_ufw_rules_always }}"
    ufw_commentprefix: "{{ alb_ufw_commentprefix }}"
    name_of_rules: "alb_ufw_rules_always"
  when:
    - "alb_ufw_rules_always is defined"
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "ufw | Rules alb_ufw_rules"
  include: rules.yml
  vars:
    ufw_rules: "{{ alb_ufw_rules }}"
    ufw_commentprefix: "{{ alb_ufw_commentprefix }}"
    name_of_rules: "alb_ufw_rules"
  when:
    - "alb_ufw_rules is defined"
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: ufw | allow-dmz.yml
  include: allow-dmz.yml
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"
    - alb_ufw_autoapply_dmz is sameas true

- name: ufw | allow-bastion-hosts.yml
  include: allow-bastion-hosts.yml
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"
    - alb_ufw_autoapply_bastion_hosts is sameas true

- name: ufw | allow-jump-boxes.yml
  include: allow-jump-boxes.yml
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"
    - alb_ufw_autoapply_jump_boxes is sameas true

- name: ufw | default-policies.yml
  include: default-policies.yml
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

## @see https://github.com/ansible/ansible/issues/45446

- name: ufw | Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

# TASK [ap-application-load-balancer : Configure the kernel to keep connections alive when enabling the firewall] ********************
#  [WARNING]: The value 1 (type int) in a string field was converted to '1' (type string). If this does not look like what you
# expect, quote the entire value to ensure it does not change.
# 
# fatal: [apps_server_apalbdemo]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: kernel.panic = 10\nnet.ipv6.conf.all.disable_ipv6 = 1\nsysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal: No such file or directory\n"}

#- name: "UFW state {{ alb_ufw_state | default (alb_ufw_state__default) }}"
#  ufw:
#    state: "{{ alb_ufw_state | default (alb_ufw_state__default) }}"

- name: "ufw | UFW state enabled"
  ufw:
    state: "enabled"
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

## ufw status verbose  (after) ________________________________________________
- name: "ufw | ufw status verbose (after)"
  shell: "ufw status verbose"
  become: "yes"
  changed_when: false
  register: ufw_status_verbose2
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"

- name: "ufw | ufw status verbose print (after)"
  debug: var=ufw_status_verbose2.stdout_lines
  when:
    - "(alb_ufw_facts_deployed is changed) or (alb_forceredeploy|bool)"
