---
# tasks/ufw/main.yml

- name: clusterfuck-pre-check.yml
  include: clusterfuck-pre-check.yml

## ufw status verbose  (before) ________________________________________________
- name: "ufw status verbose (before)"
  shell: "ufw status verbose"
  become: "yes"
  changed_when: false
  register: ufw_status_verbose1

- name: "ufw status verbose print (before)"
  debug: var=ufw_status_verbose1.stdout_lines

- name: install-ufw.yml
  include: install-ufw.yml

- name: ufw-reset.yml
  include: ufw-reset.yml
  when: 
    - "alb_ufw_canreset is defined and alb_ufw_canreset is sameas true"
    - "alb_ufw_reset is defined and alb_ufw_canreset is sameas true"

- name: "ALB/UFW/Rules alb_ufw_rules_always"
  include: rules.yml
  vars:
    ufw_rules: "{{ alb_ufw_rules_always }}"
    ufw_commentprefix: "{{ alb_ufw_commentprefix }}"
    name_of_rules: "alb_ufw_rules_always"
  when: "alb_ufw_rules_always is defined"

- name: "ALB/UFW/Rules alb_ufw_rules"
  include: rules.yml
  vars:
    ufw_rules: "{{ alb_ufw_rules }}"
    ufw_commentprefix: "{{ alb_ufw_commentprefix }}"
    name_of_rules: "alb_ufw_rules"
  when: "alb_ufw_rules is defined"

- name: allow-dmz.yml
  include: allow-dmz.yml

- name: allow-bastion-hosts.yml
  include: allow-bastion-hosts.yml

- name: allow-jump-boxes.yml
  include: allow-jump-boxes.yml

- name: default-policies.yml
  include: default-policies.yml

- name: "UFW state {{ alb_ufw_state | default (alb_ufw_state__default) }}"
  ufw:
    state: "{{ alb_ufw_state | default (alb_ufw_state__default) }}"

## ufw status verbose  (after) ________________________________________________
- name: "ufw status verbose (after)"
  shell: "ufw status verbose"
  become: "yes"
  changed_when: false
  register: ufw_status_verbose2

- name: "ufw status verbose print (after)"
  debug: var=ufw_status_verbose2.stdout_lines

- name: clusterfuck-post-check.yml
  include: clusterfuck-post-check.yml